# Generated by Django 2.2.5 on 2020-07-09 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cat_model_q',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_name', models.CharField(max_length=50)),
                ('q_icon', models.ImageField(upload_to='Blog_cat_icon/')),
                ('q_slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='postmodel_q',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qname', models.CharField(max_length=255)),
                ('q_slug', models.SlugField(max_length=255, unique=True)),
                ('decribe_post', models.TextField(blank=True)),
                ('post_img', models.ImageField(upload_to='media_blog/')),
                ('post_views', models.IntegerField(blank=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('catagry_select', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='QandS.cat_model_q')),
            ],
        ),
    ]
