# Generated by Django 2.2.5 on 2020-07-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QandS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='q_shotlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shot_list_name', models.CharField(max_length=255)),
                ('shot_list_data', models.URLField(blank=True, default='emty')),
            ],
        ),
    ]
