# Generated by Django 2.2.5 on 2020-07-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QandS', '0002_q_shotlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='q_shotlist',
            name='awnsr_qna',
            field=models.TextField(blank=True),
        ),
    ]
