# Generated by Django 2.2.5 on 2020-07-12 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QandS', '0004_auto_20200711_1908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cat_model_q',
            old_name='q_name',
            new_name='publisher',
        ),
    ]
