# Generated by Django 2.2.5 on 2020-07-12 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QandS', '0005_auto_20200712_0936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmodel_q',
            old_name='catagry_select',
            new_name='catagry',
        ),
    ]
