# Generated by Django 2.2.5 on 2020-07-23 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QandS', '0008_auto_20200723_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmodel_q',
            old_name='post_img',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='postmodel_q',
            old_name='post_views',
            new_name='view',
        ),
    ]
