# Generated by Django 2.2.5 on 2020-07-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QandS', '0009_auto_20200723_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel_q',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
