# Generated by Django 2.2.5 on 2020-08-02 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QandS', '0010_postmodel_q_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat_model_q',
            name='q_icon',
        ),
        migrations.RemoveField(
            model_name='postmodel_q',
            name='photo',
        ),
    ]
