# Generated by Django 2.2.5 on 2020-08-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QandS', '0012_auto_20200803_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel_q',
            name='SeoMetaDes',
            field=models.CharField(blank=True, max_length=155),
        ),
        migrations.AddField(
            model_name='postmodel_q',
            name='SeoTitle',
            field=models.CharField(blank=True, max_length=155),
        ),
    ]
