# Generated by Django 2.2.5 on 2020-07-01 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cat_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=50)),
                ('cat_full_data', models.URLField(blank=True, default='No link')),
                ('cat_icon', models.ImageField(upload_to='Blog_cat_icon/')),
                ('cat_slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='postmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('blog_slug', models.SlugField(max_length=255, unique=True)),
                ('decribe_post', models.TextField(blank=True)),
                ('post_img', models.ImageField(upload_to='media_blog/')),
                ('post_views', models.IntegerField(blank=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('catagry_select', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Blog.cat_model')),
            ],
        ),
    ]
