# Generated by Django 2.2.5 on 2020-07-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat_model',
            name='cat_description',
            field=models.CharField(default='No data', max_length=50),
        ),
    ]
