# Generated by Django 2.2.5 on 2020-08-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_cat_model_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat_model',
            name='SeoMetaDes',
            field=models.CharField(blank=True, max_length=155),
        ),
        migrations.AddField(
            model_name='cat_model',
            name='SeoTitle',
            field=models.CharField(blank=True, max_length=155),
        ),
        migrations.AddField(
            model_name='cat_model',
            name='Seoimgalt',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='SeoMetaDes',
            field=models.CharField(blank=True, max_length=155),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='SeoTitle',
            field=models.CharField(blank=True, max_length=155),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='Seoimgalt',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
