# Generated by Django 2.2.5 on 2020-08-07 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mobileGoole_AdsPagename',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PageName', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='webGoole_AdsPagename',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PageName', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='web_version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ad_Code', models.TextField(blank=True)),
                ('Created', models.DateField(auto_now_add=True)),
                ('Ads_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GooleAd.webGoole_AdsPagename')),
            ],
        ),
        migrations.CreateModel(
            name='mobile_version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ad_Code', models.TextField(blank=True)),
                ('Created', models.DateField(auto_now_add=True)),
                ('Ads_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GooleAd.mobileGoole_AdsPagename')),
            ],
        ),
    ]
