# Generated by Django 2.2.5 on 2020-08-07 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0004_channelseo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel_pageseo',
            name='Channel_Name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seo.ChannelSeo'),
        ),
    ]
