# Generated by Django 2.2.5 on 2020-03-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcreate',
            name='release_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
