# Generated by Django 2.2.5 on 2020-06-22 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Data_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag_createors',
            name='selet_channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Data_app.Channel'),
        ),
    ]
