# Generated by Django 2.2.5 on 2020-06-22 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Data_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcreate',
            name='tag_creator',
            field=models.ManyToManyField(default='0', to='Data_app.tag_createors'),
        ),
        migrations.AlterField(
            model_name='tag_createors',
            name='main_tag_select',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Data_app.tag_data'),
        ),
    ]
