# Generated by Django 2.2.5 on 2020-04-09 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Data_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcreate',
            name='mobilebrand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Data_app.Cetagroy_list'),
        ),
    ]
