# Generated by Django 2.2.5 on 2020-04-09 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Data_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cetagroy_list',
            old_name='Brand_profile',
            new_name='Brand_profiles',
        ),
    ]
