# Generated by Django 2.2.5 on 2020-03-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='slug_channel',
            field=models.CharField(default=1, max_length=33),
            preserve_default=False,
        ),
    ]
