# Generated by Django 2.2.5 on 2020-06-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag_data',
            name='tag_name_d',
        ),
        migrations.AddField(
            model_name='tag_data',
            name='tag_content_link',
            field=models.URLField(blank=True, unique=True),
        ),
    ]
