# Generated by Django 2.2.5 on 2020-06-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag_data',
            name='query_slug',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
