# Generated by Django 2.2.5 on 2020-06-19 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Data_app', '0002_auto_20200619_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcreate',
            name='tag',
        ),
    ]
