# Generated by Django 2.2.5 on 2020-03-31 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_app', '0002_channel_slug_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcreate',
            name='view',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
