# Generated by Django 2.2.5 on 2020-04-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_app', '0003_auto_20200409_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='ChannelLink',
            field=models.CharField(blank=True, max_length=300, unique=True),
        ),
    ]
