# Generated by Django 2.2.5 on 2020-06-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_app', '0003_remove_postcreate_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcreate',
            name='tag',
            field=models.CharField(max_length=233, null=True),
        ),
    ]
