# Generated by Django 2.2.5 on 2020-04-12 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Data_app', '0004_channel_channellink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='ChannelLink',
        ),
    ]
