# Generated by Django 2.2.5 on 2020-04-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_app', '0005_remove_channel_channellink'),
    ]

    operations = [
        migrations.AddField(
            model_name='cetagroy_list',
            name='ChannelDataUrl',
            field=models.CharField(blank=True, max_length=300, unique=True),
        ),
    ]
