# Generated by Django 2.2.5 on 2020-08-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_app', '0020_cetagroy_list_seoimgalt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag_createors',
            name='tag_name',
            field=models.CharField(blank=True, default=1, max_length=233),
            preserve_default=False,
        ),
    ]
